services:
  app:
    container_name: tagfolio-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_PROFILES_ACTIVE=test # Changed to 'test' as this file is used for the TEST environment

  db:
    container_name: tagfolio-db
    build:
      context: ./docker/db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=${DB_PASSWORD}
      - APP_USER=${DB_USER}
      - APP_USER_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 20 # Increased retries
      start_period: 60s # Added start_period to give DB more time to initialize

volumes:
  db_data:
